### PR TITLE
[New Talk] Update README.md

### PR DESCRIPTION
**Pull request by mmphego**
Added James Powells PyData talk, titled: What Does It Take To Be An Expert At Python?

### CODE REVIEW

**Comment by hellerve** [comment]
Hey @mmphego! Thank you for your contribution 🎉 

I haven’t forgotten about you, but I haven’t had time to watch the talk yet. I’ll probably watch it today or tomorrow, and then merge it.

**Comment by mmphego** [comment]
Hey @hellerve 
Hope you enjoy the talk, as much as I did.

**Comment by hellerve** [comment]
This was fun! Thank you for proposing this!

**Comment by mmphego** [comment]
You are welcome.

**Pull request merged**
