### PR TITLE
Add function and architecture talks

### PR DESCRIPTION
**Pull request by talyssonoc**

### CODE REVIEW

**Comment by hellerve** [comment]
Hello @talyssonoc and thanks for your contribution! I will look at the talks in the coming days and get back to you!

**Comment by talyssonoc** [comment]
Thank you, @hellerve!

**Comment by hellerve** [comment]
Minor nitpick: I would put a period after Robert Martin’s middle name.

Status update: I’ve listened to the first talk on the list; I’m not a fan of Robert C. Martin, but he is a great public speaker!

**Comment by talyssonoc** [comment]
Thank for the update @hellerve! I just added the period after the "C" 😄

**Comment by hellerve** [comment]
Perfect, thank you! I will probably watch the last talk in the list (by Mark Seemann) tomorrow.

**Comment by hellerve** [comment]
I merged this a little absent-mindedly yesterday! Of course I wanted to thank you for your contribution, sorry that I didn’t do that when merging! 😸

**Comment by talyssonoc** [comment]
Hahaha there's no problem! Thank you for keeping that awesome list, I've watched some and intend to watch even more :smile:

**Pull request merged**
