### PR TITLE
"How to be a Happy Developer"

### PR DESCRIPTION
**Pull request by perdian**
Got pretty good feedback on the talk.

### CODE REVIEW

**Comment by hellerve** [comment]
Hey, thank you for your contribution, and congratulations on the successful talk!

FYI, I probably won’t be able to get to watching the talks until later today. I’ll get back to you as soon as I’ve watched them! Something I can already say is that the ordering seems to be off—the talks are ordered by date, so your talk from 2019 would go right at the top of the section!

**Comment by perdian** [comment]
> Something I can already say is that the ordering seems to be off—the talks are ordered by date, so your talk from 2019 would go right at the top of the section!

Ah, didn't notice that. Fixed it!

**Comment by hellerve** [comment]
This was fun, thank you!

**Comment by perdian** [comment]
> This was fun, thank you!

Thanks, glad you enjoyed it.

**Pull request merged**
