### PR TITLE
HTTPS-ify a dozen, deduplicate 3, add 1

### PR DESCRIPTION
**Pull request by nayuki**
My commit comments and diffs fully explain the changes. Feel free to approve/reject any subset.

Thanks for your work in maintaining this collection of links to educational resources.

### CODE REVIEW

**Comment by hellerve** [comment]
Thank you for this! The changes all look very useful.

Just FYI: I probably won’t get to watching the talk you’d like to add before later today. As soon as I did that I’ll get back to you on this PR!

**Comment by hellerve** [comment]
It looks like the talk you added is not in order: the talks are ordered by date, and the talk you’ve linked to has to move up the list a bit!

**Comment by hellerve** [comment]
It also seems like the talk was given at a 2010 conference, which would mean that we’d have to adjust the date as well!

**Comment by nayuki** [comment]
Wow, I didn't expect that you'd personally watch and review every video before adding them!
Anyhow, I made the fixes you requested.

**Comment by hellerve** [comment]
Thank you so much! It looks great to me now ❤️

**Pull request merged**
