### PR TITLE
Adding data-oriented design talk

### PR DESCRIPTION
**Pull request by pepasflo**
Thanks to @catb0t for the suggestion and markdown snippet!

### CODE REVIEW

**Comment by hellerve** [comment]
That’s perfect! Do you want to add a link to the other list as well or would you prefer if I merged this as is? I’m happy to do either!

**Comment by pepasflo** [comment]
Oh, I'm actually not sure how you'd like to format a link to list of videos.  You can go ahead and merge this as-is for now.

**Review by hellerve — APPROVED** [review]
Thank you 🎉

**Comment by catb0t** [comment]
@pepasflo just  for future reference, such links already exist at the top of JavaScript and Python sections 

```
#### JavaScript
(There is a good list of talks about JS to be found [here](https://github.com/bolshchikov/js-must-watch))
```

you can do the same in a PR, if you like

**Comment by hellerve** [comment]
That’s pretty free-form. Last time I did it like this:
```markdown
(There is a good list of talks about <x> to be found [here](mylink))
```
but I’m not super happy with the phrasing anymore. Maybe @catb0t has some ideas/insights on this, since they’ve been really good at fixing my phrasing.

**Comment by hellerve** [comment]
Oh, @catb0t jinx’d me!

**Comment by catb0t** [comment]
Heh, we commented the same thing at the same time. I'm glad you appreciate my re-wording :)

**Pull request merged**
