### PR TITLE
Add "Why Isn't Functional Programming the Norm?" talk by Richard Feldman

### PR DESCRIPTION
**Pull request by alexbrbr**

### CODE REVIEW

**Comment by hellerve** [comment]
Thanks for your contribution!

I think this is one of those talks that you can listen to without looking and I’d like to add `[A]` at the end, what do you think?

**Comment by alexbrbr** [comment]
Yes it's possible to listen to the talk without looking at it, even if you would miss the charts & picture you would still get the idea of the talk in my opinion :)

**Comment by hellerve** [comment]
Do you want to add that? Otherwise I’d be happy to merge it as-is and add it myself.

**Comment by alexbrbr** [comment]
Done, thanks for your patience and explanations 😄

**Comment by hellerve** [comment]
Perfect! Thank you for contributing!

**Review by hellerve — APPROVED** [review]

**Pull request merged**
