### PR TITLE
adds Emily Freeman's Failover conf talk

### LINKED ISSUE #104: Add "What's Next for DevOps"
Emily Freeman's FailoverConf talk - "What's next for Devops" would be a great addition – I think.

https://www.youtube.com/watch?v=_Zydz0__KA8

Thoughts?

### PR DESCRIPTION
**Pull request by justisGipson**
What's Next for DevOps?

I figured I'd just open this up, if that's ok?

### CODE REVIEW

**Review by hellerve — APPROVED** [review]
Looks great! I think this can be listened to without necessarily watching the screen, what do you think? If so, we can add an `[A]`

**Comment by justisGipson** [comment]
I agree. I can make the change, or you can if you want

**Comment by hellerve** [comment]
Go ahead, this is your PR :)

**Comment by hellerve** [comment]
Thank you!

**Pull request merged**
