### PR TITLE
Fixing inter-year-group spacing

### LINKED ISSUE #69: Github Markdown doesn't render extra newlines as <br>
I never bothered to check that my simplistic method of breaking up the groups of talks actually rendered correctly in Github. It looks right in my editor's GH Markdown renderer though.

The solution is quite ugly, along the lines of 

```markdown
* [-Os matters](https://www.youtube.com/watch?v=vGV5u1nxqd8) [00:44:12] by **Mark Zeren** (2018)

<br/>

* [10 Core Guidelines You Need to Start Using Now](https://www.youtube.com/watch?v=XkDEzfpdcSg) [01:02:32] by **Kate Gregory** (2017)
```
I'm still testing the semantics but I'll make a pull to fix it, because currently the extra newlines make *every* bullet have too much spacing.

### PR DESCRIPTION
**Pull request by catb0t**
closes #69 

New format noted in the contrib paragraph, and I changed `<chrono>` to `&lt;chrono&gt;` because GH Markdown sees it as a HTML tag when there is `<br>` in the file.

Check the rich diff and you'll see what I mean.

### CODE REVIEW

**Comment by hellerve** [comment]
That’s weird, that’s why they are escaped! Anyway, thanks for that fix. I’m not super happy that we have to insert HTML, but there seems to be no other option (usually two empty lines should fix it, but that doesn’t seem to work). Alternatively, we could alternate between list styles, i.e.:

```markdown
* hi
* also hi

+ bye
+ also bye
```

which seems to render fine, but is just as ugly if not uglier. I’ll let you voice your opinion before I merge, though!

**Comment by catb0t** [comment]
Alternating list styles would be cleaner except I think it's more complex to explain. Also, the entire section has to have one list style, or else they get broken up anyway:

```
* hi
* also hi
+ bye
* also bye
* again bye
```
gives 
* hi
* also hi
+ bye
* also bye

**Comment by catb0t** [comment]
Alternating list styles would be cleaner if we could have just the first one be different  (although I think it's more complex than `<br>` to explain anyway). Unfortunately, the entire section has to have one list style, or else they get broken up even without a newline:

```
* hi
* also hi
+ bye
* also bye
* again bye
```
gives 
* hi
* also hi
+ bye
* also bye
* again bye

It will be harder to maintain and add to if the list style isn't homogenous, and breaks if you put a `*` instead of `+`. I don't like it either, but I  think `<br>` is the way to go.

**Comment by hellerve** [comment]
Alright then, seems like we’ve reached an agreement!

**Comment by catb0t** [comment]
I think so. :)

**Pull request merged**
