### PR TITLE
Dependently Typed Functional Programming in Idris by David Christiansen

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by hellerve** [comment]
Thanks for the contribution!

I will look at the talk today. Just a quick question: Do you know where the other parts are and if so, could you maybe make this a talk group as I did [here](https://github.com/hellerve/programming-talks/commit/0c4c961929c7b97d49bffd80a0eb134580e239f3#diff-04c6e90faac2675aa89e2176d2eec7d8L93)?

**Comment by catb0t** [comment]
Part 2: https://vimeo.com/117973383 [1:02:47]
Part 3: https://vimeo.com/117979741 [58:14]

I might consider making a PR myself for these changes but I don't know what you mean by "talk group" as you did in that commit ?

**Comment by hellerve** [comment]
What I meant was having a layout like this:

 * **Dependently Typed Functional Programming in Idris**: This talk has three parts.
   * [Dependently Typed Functional Programming in Idris, Part 1](https://vimeo.com/117221082) [01:20:29] by **David Christiansen**
   * [.. Part 2 etc. ...]

Just to have a consistent layout for a layout for multiple related talks. Is that clearer?

**Comment by catb0t** [comment]
Oh, that makes sense now (I guess it wasn't very clear from the raw markdown source).

**Comment by hellerve** [comment]
No worries, all is well. I'm known to not provide enough information when something is clear to me.

**Comment by hellerve** [comment]
Superseded by #35.

**Pull request closed without merging**
