### PR TITLE
Add  'Concurrency Is Not Parallelism' by Rob Pike

### PR DESCRIPTION
**Pull request by pmatseykanets**
One of the best talks explaining the difference between these two related but so different concepts

### CODE REVIEW

**Comment by hellerve** [comment]
Hey! Thanks for your contribution!

I watched the talk a while ago and think it’s technically a great explanation of concurrency and parallelism. I was hesitant to add it, though,—and I still am—because the base metaphor is so inflammatory. I dont’t think it’s particularly friendly to use "burn books for <programming language X>" as the foundation for one’s talk, and it might not be super helpful to get your point across. I certainly felt taken aback, and I haven’t programmed in C++ in a while.

That said, I’d like to leave this open so that other people can voice their opinions on this. Maybe I’m wrong or just too easily offended, and the crowd disagrees with me!

**Comment by pmatseykanets** [comment]
Sure, no worries.
Although I may see that the metaphor in question is not the best one but I don't see at as inflammatory.
In any case thanks for keeping an open mind and letting others to weigh in.

**Comment by catb0t** [comment]
Personally I think it's funny that Rob Pike wants to pick on C++ since he obviously doesn't like it very much, and maybe he gets away with it because he's Rob Pike. 

I really don't think it's the foundation or base metaphor of the talk either, there's good serious points before and in the rest of the talk after that example, and that example is only used for ~5 minutes in 1 (or 2?) place/s.

**Comment by hellerve** [comment]
Alright, maybe I’m just too sensitive when it comes to burning books 😸 

I’m just very wary of people who want to pick on other people’s choice of technology—for whatever reason—, but I guess there are a bunch of other talks on the list as well where the speaker derides another technology. It’s a bit of a useless restriction, I guess.

If y’all are seeing the merit despite of the—perceived (by me)—flaws, then that’s good enough for me.

**Comment by hellerve** [comment]
Thanks again for your contribution, @pmatseykanets, and your insight, @catb0t!

**Pull request merged**
