### PR TITLE
adds solid ground talk on elixir by sasa juric

### PR DESCRIPTION
**Pull request by b-m-f**
Added the year in a second commit. Could start now to incrementally get years included.

### CODE REVIEW

**Comment by hellerve** [comment]
Good strategy. I’d opt for putting it behind the name, like so:
 ```
[...] by **Person** (year)
```

**Comment by hellerve** [comment]
Any particular reason you included the timestamp at 1 second?

**Comment by b-m-f** [comment]
Good idea. I will change this and add a third commit. 

&& nope. Good catch on that 👍

**Comment by hellerve** [comment]
Thank you! I took the liberty of squashing the commits into a single one :)

**Pull request merged**
