### PR TITLE
add Boundaries by Gary Bernhardt

### PR DESCRIPTION
**Pull request by JackAWatt**
I found this talk interesting and didn't see it on the list.

### CODE REVIEW

**Comment by hellerve** [comment]
Thanks for the addition, highly appreciated!

I'm not sure `Miscellaneous` is the right category for it, though. I would either put it into Python because of the code—it might not be easily digestible for some people without knowledge of these languages—or under `Software Development`. Software Development is arguably just a little less awful, because it's also way too generic, but it's at least a little more specific than miscellaneous.

Cheers

**Comment by hellerve** [comment]
Actually, thinking about the talk some more, I wouldn't opt for putting it into the `Python` section, because of the Ruby parts. I might have been a little presumptuous to assume one can read Ruby if they know Python (or vice versa).

**Comment by JackAWatt** [comment]
I put the talk in `Miscellaneous` because there were already talks by Gary Bernhardt there. Should I change it to `Software Development`? I agree that it would be more fitting.

**Comment by hellerve** [comment]
That would be great, thank you!

**Comment by JackAWatt** [comment]
I just moved it to `Software Development`

**Comment by hellerve** [comment]
Thank you! 👍

**Pull request merged**
