### PR TITLE
Update accurate time of Intro end for Mike Solomon

### PR DESCRIPTION
**Pull request by ketanbhatt**

### CODE REVIEW

**Comment by hellerve** [comment]
Rewatching this, isn‘t it 10:12?

**Comment by ketanbhatt** [comment]
9:12 is when the conference host starts to introduce Solomon, I think that's a good point for the video to start to give people context as well.

**Comment by hellerve** [comment]
That makes sense! Should we also update the video link with a timestamp there? People will be able to go back if they want, but we spare them a few seconds of searching around.

**Comment by hellerve** [comment]
Anyway, thank you for your contribution!

Sorry if I’m a little curt, I’m on my honeymoon in Iceland at the moment, and the internet situation has been less than ideal.

**Comment by ketanbhatt** [comment]
Hey @hellerve no you sound perfectly fine! 😃 

I have updated the PR to also make the link start at the right time. 

Enjoy your honeymoon :)

**Comment by hellerve** [comment]
Perfect, thanks for your work on this!

**Pull request merged**
