### PR TITLE
add talk by Leeren Chang on VimL

### PR DESCRIPTION
**Pull request by amitech**

### CODE REVIEW

**Comment by amitech** [comment]
@hellerve please review.

**Comment by hellerve** [comment]
Hey @amitech, thanks for your submission!

I’ll watch the talk today, sadly I had no time yesterday (I had already watched the two talks in #90), but it’s open already and I hope I can get to it this evening.

**Comment by amitech** [comment]
Okay, do you have written any article regarding how to get motivation to watch full talk without distractions?

**Comment by hellerve** [comment]
Hey! I don’t have one, but that sounds like an interesting idea!

For me the two most important factors are:
- Taking a lot of notes: this helps me memorize, and I can go back to the notes when I need them. And, it gives me something to do that prevents me from checking my phone or other similar things.
- Knowing when to take breaks: The cool thing about recorded talks is that I can take a break whenever I need one. If there is an interesting idea that I want to pursue or think about for a while, or if there is something I’m not sure I understand, or even if it’s just a lot of information all at once, I can just press pause and take a break. That helps a lot.

I hope that helps a little bit!

**Review by hellerve — APPROVED** [review]
This was a fun watch! I moved away from tmux a while ago, but maybe I should go back!

Vim has been my primary editor for about 7 years now, and this talk articulated some of the things I’ve been wanting to advocate for, but haven’t been able to express.

**Comment by amitech** [comment]
> Hey! I don’t have one, but that sounds like an interesting idea!
> 
> For me the two most important factors are:
> 
>     * Taking a lot of notes: this helps me memorize, and I can go back to the notes when I need them. And, it gives me something to do that prevents me from checking my phone or other similar things.
> 
>     * Knowing when to take breaks: The cool thing about recorded talks is that I can take a break whenever I need one. If there is an interesting idea that I want to pursue or think about for a while, or if there is something I’m not sure I understand, or even if it’s just a lot of information all at once, I can just press pause and take a break. That helps a lot.
> 
> 
> I hope that helps a little bit!

Yes, it helps. Thanks for information. You are right, short breaks are awesome.

**Pull request merged**
