### PR TITLE
Remove unavailable video: Sharding and Scaling Your Database

### PR DESCRIPTION
**Pull request by atiabbz**

### CODE REVIEW

**Comment by hellerve** [comment]
Good catch, thanks! Bummer that it is gone.

**Review by hellerve — APPROVED** [review]

**Comment by katrinleinweber** [comment]
It's still available to play on http://web.archive.org/web/20171024050158/https://www.youtube.com/watch?v=p3ytSdUQZzA ✌️

**Comment by hellerve** [comment]
@katrinleinweber Oh neat, I didn’t know archive.org was caching whole videos!

Do you want to re-add it? If not, I’d be happy to do it.

**Comment by katrinleinweber** [comment]
Testing to download it first… Let's re-add it, if the video file is complete.

**Pull request merged**
